name:
on:
  push:
    branches:
      - main
  workflow_dispath:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: custom actions
        run: echo "Hello world"
        shell: bash
  goodbye:
    runs-ons: 
    steps:
      - name: goodby world
        run: echo "good bye"  
        shell: bash

